refactor validation logic to download urls and verify distfiles integrity

diff --git a/sboports b/sboports
--- a/sboports
+++ b/sboports
@@ -20,7 +20,7 @@
 # Rogério Girão rogeriogirao1@proton.me
 #
 NAME=$(basename "$0")
-VERSION=1.1.2
+VERSION=1.1.3
 LOCAL_DIR="/var/lib"
 REPO_NAME="slackbuilds"
 REPO_DIR="$LOCAL_DIR/$REPO_NAME"
@@ -40,32 +40,42 @@ dir_check() {
 		return 1
 }
 
+validate_url() {
+	case "$1" in
+		http://*|https://*|ftp://*)
+			if wget --spider -q "$1"; then
+				return 0
+			fi
+			;;
+		*)
+			echo "Ignoring invalid entry: $1"
+			;;
+	esac
+	return 1
+}
+
+try_urls() {
+	found=0
+	for url in $@; do
+		if validate_url "$url"; then
+			file=$(basename "$url")
+			echo "Distfile found at: $url"
+			wget -N "$url" || error "Failed to download $url"
+			found=1
+		fi
+	done
+
+	[ "$found" -eq 1 ] && return 0 || return 1
+}
+
 pkg_fetch() {
 	if dir_check; then
 		source "$PKG_NAME.info"
+		if ! try_urls $DOWNLOAD; then
+				echo "No valid url found. Trying with DOWNLOAD_x86_64"
 
-		validate_url() {
-			for url in "$@"; do
-				case "$url" in
-					http://*|https://*|ftp://*)
-						if wget -c "$url"; then
-							return 0
-						else
-							echo "Failed to download: $url"
-						fi
-						;;
-					*)
-						echo "Ignoring invalid entry: $url"
-						;;
-				esac
-			done
-			return 1
-		}
-
-		if ! validate_url $DOWNLOAD; then
-			echo "Trying fallback with DOWNLOAD_x86-64..."
-			if ! validate_url $DOWNLOAD_x86_64; then
-				error "Failed to download distfiles."
+			if ! try_urls $DOWNLOAD_x86_64; then
+				error "No valid url found"
 			fi
 		fi
 	else
@@ -73,29 +83,33 @@ pkg_fetch() {
 	fi
 }
 
-hashes_extract() {
-	if dir_check; then
-		source "$PKG_NAME.info"
-		for url in $DOWNLOAD; do
-			distfile=$(basename "$url")
-			src=$(ls | grep -w "$distfile")
-			if [ -z "$src" ]; then
-				echo "Distfile \"$distfile\" missing. Downloading..."
-				wget "$url"
-				src=$(ls | grep -w "$distfile")
+download_missing() {
+	for url in $@; do
+		if validate_url "$url"; then
+			if [ -f $(basename "$url") ]; then
+				hashes_arr+=("$(md5sum "$(basename "$url")" | awk '{print $1}')")
+			else
+				echo "Downloading missing distfile from: $url"
+				if wget -nc "$url"; then
+					hashes_arr+=("$(md5sum "$(basename "$url")" | awk '{print $1}')")
+				else
+					error "Failed to download missing distfile."
+				fi
 			fi
-			hashes+="$(md5sum "$src" | awk '{print $1}') "
-		done
-	else
-		error "Error: You are not inside the SlackBuilds tree."
-	fi
+		fi
+	done
+}
+
+extract_hashes() {
+	source "$PKG_NAME.info"
+	download_missing $DOWNLOAD
+	download_missing $DOWNLOAD_x86_64
+	md5sums=$(echo "$MD5SUM" "$MD5SUM_x86_64" | grep -oE '\b[a-fA-F0-9]{32}\b')
+	md5sum_arr=($md5sums)
 }
 
 pkg_checksum() {
-	hashes_extract
-	hashes_arr=($hashes)
-	md5sum_arr=($MD5SUM)
-
+	extract_hashes
 	echo "Verifying md5sums..."
 	for ((i = 0; i < "${#md5sum_arr[@]}"; i++)); do
 		if [ "${hashes_arr[$i]}" == "${md5sum_arr[$i]}" ]; then
@@ -114,7 +128,8 @@ pkg_build() {
 
 pkg_install() {
 	if dir_check; then
-		pkg_file=$(find /tmp -maxdepth 1 -type f -name "$PKG_NAME*" | sort -V | tail -n1)
+		source "$PKG_NAME.info"
+		pkg_file=$(sniff /tmp -t f -p "$PRGNAM-$VERSION")
 		if [ ! -z "$pkg_file" ]; then
 			echo "Package $PKG_NAME found at $pkg_file"
 			read -p "Do you want to install/reinstall it? [y/N] " answer
@@ -125,6 +140,12 @@ pkg_install() {
 			fi
 		fi
 		pkg_build
+		pkg_file=$(sniff /tmp -t f -p "$PRGNAM-$VERSION")
+		if /sbin/upgradepkg --reinstall --install-new "$pkg_file"; then
+			echo "Package installed/reinstalled successfully."
+		else
+			error "Failed to install package"
+		fi
 	else
 		error "Error: You are not inside the SlackBuilds tree."
 	fi
