remove old show_pkg_status(); add new pkg_fetch()

diff --git a/sboports b/sboports
--- a/sboports
+++ b/sboports
@@ -40,14 +40,16 @@ dir_check() {
 		return 1
 }
 
-show_pkg_status() {
-	local -n installed_ref=$1
-	local pkg="$2"
-
-	if [ ! -z $(printf "%s\n" "${installed_ref[@]}" | grep -w "$pkg") ]; then
-		echo "[ installed ] - $pkg"
+pkg_fetch() {
+	if dir_check; then
+		source "$PKG_NAME.info"
+		for url in $DOWNLOAD; do
+			if ! wget "$url"; then
+				error "Failed to fetch the distfiles"
+			fi
+		done
 	else
-		echo "[uninstalled] - $pkg"
+		error "Error: You are not inside the slackbuilds tree"
 	fi
 }
 
